<?php

// Script to generate the OpenNAC Ansible Vars file to deploy a migrated 1.2.2 infraestructure


//--------------------------- 
//   FUNCTIONS  
//---------------------------





//--------------------------- 
//   START OF EXECUTION   
//---------------------------

//The idea is to parse all the 1.2.1 config and put into vars YAML file used to deploy an OpenNAC infraestructure so the new nodes will mantain the old ones config
// We can use the IPs defined in /etc/hosts to get the maximum of variables connecting to each node of the infraestructure and get the values (example: proxy config, clients.conf)


//1rst we wull read and parse all the information on /etc/hosts
/*
127.0.0.1       onmaster
127.0.0.1       oncore
10.10.36.82     on2 onslave
10.10.36.81     onanalytics
10.10.36.81     onaggregator
10.10.36.147    onsensor
*/

$mastersArray = array();
$slavesArray = array();
$aggregatorsArray = array();
$analyticsArray = array();
$sensorsArray = array();

$hosts = fopen("/etc/hosts", "r");

if ($hosts) {
    while (($line = fgets($hosts)) !== false) {
        // ((?:[0-9]{1,3}\.){3}[0-9]{1,3})\s+(.*[^\s])

        if (preg_match('/((?:[0-9]{1,3}\.){3}[0-9]{1,3})\s+(.*[^\s])/', $lines, $hostMatch)){ 
            echo "\nHost -> "; echo $hostMatch[1] . " --> " . $hostMatch[0] . "\n";
        }


    }
    fclose($hosts);
} else {
    // error opening the file.
    echo "Can't open /etc/hosts file \n\n";
} 

// -------------------------------------------------->>>    YAML EXAMPLE
/*

################
# INSTALLATION #
################

inventory: 'static'
ntpserv1: '0.centos.pool.ntp.org' # A NTP server where you must get the synchronization

# The version packages that we want to be installed
# It could be the stable version or the testing one
# Change it if necessary
deploy_testing_version: false
repo_auth: 'user:password' # CHANGE the actual user and password


###########################
# PRINCIPAL CONFIGURATION #
###########################

criticalAlertEmail: 'notify1@opennac.org,notify2@opennac.org'
criticalAlertMailTitle: 'openNAC policy message [%MSG%]'
criticalAlertMailContent: 'Alert generated by policy [%RULENAME%], on %DATE%.\n\nData:\nMAC: %MAC%\nUser: %USERID%\nIP Switch: %SWITCHIP%\nPort: %SWITCHPORT% - %SWITCHPORTID%\n'


# Variables to configure /etc/raddb/clients.conf
clients_data: 
  - [ip: '192.168.0.0/16', shortname: 'internal192168', secret: 'testing123']
  - [ip: '10.10.36.0/24', shortname: 'internal1010', secret: 'testing123']
  - [ip: '172.16.0.0/16', shortname: 'internal17216', secret: 'testing123']
  - [ip: '10.0.0.0/8', shortname: 'internal10', secret: 'testing123']

# Variables to configure /etc/postfix/main.cf and /etc/postfix/generic
relayhostName: 'relay.remote.com'
relayhostPort: '25'
mydomain: 'acme.local'
emailAddr: 'openNAC@notifications.mycompany.com'


######################
# WORKER REPLICATION #
######################

mysql_root_password: opennac # Password for mysql root
mysql_replication_password_nagios: 'Simpl3PaSs'

# Path where will be saved files created with the script WITHOUT THE LAST "/"
# Make sure you have enough space
path: /tmp


#######################
# PROXY CONFIGURATION #
#######################

sharedkey: 'CHANGE_ME' # The string to encrypt the packets between the Proxy Servers and Backends

# PROXY.CONF
# Edit the following lines in order to configure /etc/raddb/proxy.conf
# You may either need to add new lines or to delete some.
servers_data:
  - [name: 'slv01lata', ipaddr: '10.111.16.72', secret: '{{ sharedkey }}']
  - [name: 'slv02latb', ipaddr: '10.111.16.73', secret: '{{ sharedkey }}']

pools_data:
  - [namepool: 'auth', namerealm: 'DEFAULT']

# CLIENTS.CONF
# Edit the following lines in order to configure /etc/raddb/clients.conf
# You may either need to add new lines or to delete some. 
# Follow the structure indicated below:
clients_data_PROXY:
  - [ip: '192.168.0.0/16', shortname: 'internal192168', secret: '{{ sharedkey }}']
  - [ip: '172.16.0.0/16', shortname: 'internal17216', secret: '{{ sharedkey }}']
  - [ip: '10.0.0.0/8', shortname: 'internal10', secret: '{{ sharedkey }}']

*/
